version: '3'

services: 
    php:
        container_name: task_php
        build:  ./php
        ports: 
            - 8080:80
        volumes:
            - ./www/html:/var/www/html
        depends_on: 
            - db
        
    db:
        container_name: task_mysql
        build: ./db
        ports: 
            - 3306:3306
        volumes: 
            - ./db/init:/docker-entrypoint-initdb.d
            - ./db/data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: 0529
            TZ: /Asia/Tokyo
